Fix keras load_model causing exception
With h5py 3.x causes
AttributeError: 'str' object has no attribute 'decode'

References https://github.com/tensorflow/tensorflow/issues/44467